location = /serialterminal/latest.yml {
    proxy_pass https://tst-update-package-1316411824.cos.ap-hongkong.myqcloud.com/releases/latest/latest.yml;
    proxy_ssl_server_name on;
    proxy_ssl_name tst-update-package-1316411824.cos.ap-hongkong.myqcloud.com;
    proxy_set_header Host tst-update-package-1316411824.cos.ap-hongkong.myqcloud.com;

    proxy_hide_header Cache-Control;
    add_header Cache-Control "no-cache, no-store, must-revalidate" always;
    add_header Access-Control-Allow-Origin "*" always;
}
