limit_req_zone $binary_remote_addr zone=serialterminal_activity:10m rate=10r/m;
limit_req_zone $binary_remote_addr zone=serialterminal_admin_login:10m rate=10r/m;
limit_req_zone $binary_remote_addr zone=serialterminal_update_source:10m rate=30r/m;
